# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

stages:
 - first

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

variables:
    JIRA_PASS: $JIRA_PASS
    JIRA_USER: $JIRA_USER
    TEST_HOOK: $TEST_HOOK
    PROD_HOOK: $PROD_HOOK

before_script:
    - echo $PATH
    - python -v
    - pip3 install jira-python
    - pip3 install os
    - pip3 install datetime
    - pip3 install python-dotenv

mrbtk:
  stage: first
  tags:
   - autoscale
  script:
    - python MrBTK_v2.py
